trigger:
  branches:
    include:
    - main

variables:
  BuildConfiguration: 'Release'
  ProjectPath: '**/*.csproj'

jobs:
- job: 'Default'
  displayName: Agent job 1
  pool:
    vmImage: ubuntu-20.04

  steps:
    - task: DotNetCoreCLI@2
      displayName: 'Build web project'
      inputs:
        command: 'build'
        arguments: '--configuration $(buildConfiguration)'
        projects: $(ProjectPath)
        
    # - task: DotNetCoreCLI@2
    #   displayName: 'Publish'
    #   inputs:
    #     command: publish
    #     publishWebProjects: False
    #     projects: $(ProjectPath)
    #     arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    #     zipAfterPublish: True

    - task: PublishBuildArtifacts@1
      displayName: 'Publish'
      inputs:
        pathtoPublish: '$(Build.ArtifactStagingDirectory)/viewer.zip'
        artifactName: 'viewer'
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
...