trigger:
  branches:
    include:
    - master
resources:
  repositories:
  - repository: self
    type: git
    ref: master
jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    vmImage: ubuntu-20.04
  steps:
  - checkout: self
  - task: CopyFiles@2
    displayName: Copy Files
    inputs:
      Contents: '**/*.json'
      TargetFolder: $(build.ArtifactStagingDirectory)
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
...