trigger:
  branches:
    include:
    - main
  paths:
    exclude:
    - ../app
    - ../../viewer

jobs:
- job: 'Default'
  displayName: 'Build Infrastructure'
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - task: CopyFiles@2
    displayName: Copy Files
    inputs:
      Contents: 'infrastructure/*.*'
      TargetFolder: $(build.ArtifactStagingDirectory)
  
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
...